### ISSUE TITLE
Arbitrary Signal Generator: Ch A buffer current read pointer on fpga_0.94 always read as 0

### ISSUE THREAD

**Issue by VacumMastah** [RedPitaya/RedPitaya-FPGA#1]
with /opt/redpitaya/fpga/fpga_0.93.bit the read pointer can be read,
when the signal generator is running. (command "monitor 0x40200014")

With the version fpga_0.94.bit it always reads 0x00000000

How to trigger:
  generate 1 0.5 10000 tri
  monitor 0x40200014
     --> 0x00000000 is read

  cat /opt/redpitaya/fpga/fpga_0.93.bit > /dev/xdevcfg
   generate 1 0.5 10000 tri
   monitor 0x40200014
       --> e.g. 0x0000dbb4  is read (the first read is always 0x00, too)

**Comment by juretrn** [comment]
We need to fix the documentation.
The register had to be moved to new offsets because we added a new feature in its place (very slow signal generation).

Channel A current read pointer is now at offset 0x60;
Channel A current read pointer is now at offset 0x64;
