### ISSUE TITLE
Unresolved merge conflict

### ISSUE THREAD

**Issue by tobias-riesen** [RedPitaya/RedPitaya-FPGA#2]
There are markers of a merge conflict in the code: 
* https://github.com/RedPitaya/RedPitaya-FPGA/blob/07f102008aae01c49895ec92adfe467cd1f20288/prj/Examples/make_project.tcl#L8
* https://github.com/RedPitaya/RedPitaya-FPGA/blob/07f102008aae01c49895ec92adfe467cd1f20288/prj/Examples/Frequency_counter/basic_red_pitaya_bd.tcl#L1
* Many others

**Comment by Lightsaver7** [comment]
Thank you for the note. It will be fixed.

**Comment by Lightsaver7** [comment]
I opened the pull request to fix the issue and will contact my colleagues to merge the branch.
